#!groovy
podTemplate(
label: "skopeo-pod",
        cloud: "openshift",
        inheritFrom: "maven",
        containers: [
                containerTemplate(
                        name: "jnlp",
                        image: "docker-registry.default.svc:5000/6260-jenkins/jenkins-agent-appdev",
                        resourceRequestMemory: "1Gi",
                        resourceLimitMemory: "2Gi",
                        resourceRequestCpu: "1",
                        resourceLimitCpu: "2"
    )
  ]
) {
  node('skopeo-pod') {
        def mavenCommand = "mvn -s ../nexus_settings.xml"

        stage('Checkout Source') {
            checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/Nichiro1/krivera.git']]])
        }

    // Build the Tasks Service
    dir("openshift-tasks") {
            def groupId = getGroupIdFromPom("pom.xml")
            def artifactId = getArtifactIdFromPom("pom.xml")
            def version = getVersionFromPom("pom.xml")

            def devTag = version + "-" + currentBuild.number
            def prodTag = version

            stage('Build war') {
                echo "Building version ${version}"
                sh "$mavenCommand package -DskipTests=true"
            }

      stage('Unit Tests') {
                echo "Running Unit Tests"
                sh "$mavenCommand test"
            }

     stage('Code Analysis') {
                echo "Running Code Analysis"
                sh "$mavenCommand sonar:sonar -Dsonar.host.url=http://sonarqube.gpte-hw-cicd.svc.cluster.local:9000/ -Dsonar.projectName=${JOB_BASE_NAME}-${devTag}"
            }

        stage('Publish to Nexus') {
                echo "Publish to Nexus"
                sh "$mavenCommand deploy -DskipTests=true -DaltDeploymentRepository=nexus::default::http://nexus3.gpte-hw-cicd.svc.cluster.local:8081/repository/releases"
            }

      stage('Build and Tag OpenShift Image') {
                echo "Building OpenShift container image tasks:${devTag}"

      sh "oc start-build tasks --follow --from-file=http://nexus3.gpte-hw-cicd.svc.cluster.local:8081/repository/releases/${groupId.replaceAll('\\.', '/')}/$artifactId/$version/${artifactId}-${version}.war -n 6260-tasks-dev"

        openshiftTag alias: 'false', destStream: 'tasks', destTag: devTag, destinationNamespace: '6260-tasks-dev', namespace: '6260-tasks-dev', srcStream: 'tasks', srcTag: 'latest', verbose: 'false'
            }

     stage('Deploy to Dev') {
                echo "Deploying container image to Development Project"

        sh "oc set image dc/tasks tasks=docker-registry.default.svc:5000/6260-tasks-dev/tasks:${devTag} -n 6260-tasks-dev"

      sh "oc set env dc/tasks VERSION='$devTag (tasks-dev)' -n 6260-tasks-dev"

        sh "oc delete configmap tasks-config -n 6260-tasks-dev --ignore-not-found=true"
                sh "oc create configmap tasks-config --from-file=./configuration/application-users.properties --from-file=./configuration/application-roles.properties -n 6260-tasks-dev"

      openshiftDeploy depCfg: 'tasks', namespace: '6260-tasks-dev', verbose: 'false', waitTime: '800000', waitUnit: 'sec'
                openshiftVerifyDeployment depCfg: 'tasks', namespace: '6260-tasks-dev', replicaCount: '1', verbose: 'false', verifyReplicaCount: 'false', waitTime: '', waitUnit: 'sec'
                openshiftVerifyService namespace: '6260-tasks-dev', svcName: 'tasks', verbose: 'false'
            }

        stage('Copy Image to Nexus Docker Registry') {
                echo "Copy image to Nexus Docker Registry"

      sh "skopeo copy --src-tls-verify=false --dest-tls-verify=false --src-creds openshift:\$(oc whoami -t) --dest-creds admin:redhat docker://docker-registry.default.svc.cluster.local:5000/6260-tasks-dev/tasks:${devTag} docker://nexus-registry.gpte-hw-cicd.svc.cluster.local:5000/tasks:${devTag}"

        openshiftTag alias: 'false', destStream: 'tasks', destTag: prodTag, destinationNamespace: '6260-tasks-dev', namespace: '6260-tasks-dev', srcStream: 'tasks', srcTag: devTag, verbose: 'false'
            }

      def destApp = "tasks-green"
            def activeApp = ""

        stage('Blue/Green Production Deployment') {
                activeApp = sh(returnStdout: true, script: "oc get route tasks -n 6260-tasks-prod -o jsonpath='{ .spec.to.name }'").trim()
                if (activeApp == "tasks-green") {
                    destApp = "tasks-blue"
                }
                echo "Active Application:      " + activeApp
                echo "Destination Application: " + destApp

        sh "oc set image dc/${destApp} ${destApp}=docker-registry.default.svc:5000/6260-tasks-dev/tasks:${prodTag} -n 6260-tasks-prod"

      ['blue', 'green'].each {
                    sh "oc set env dc/tasks-$it VERSION='$prodTag (tasks $it)' -n 6260-tasks-prod"
                }

      sh "oc delete configmap ${destApp}-config -n 6260-tasks-prod --ignore-not-found=true"
                sh "oc create configmap ${destApp}-config --from-file=./configuration/application-users.properties --from-file=./configuration/application-roles.properties -n 6260-tasks-prod"

                openshiftDeploy depCfg: destApp, namespace: '6260-tasks-prod', verbose: 'false', waitTime: '', waitUnit: 'sec'
                openshiftVerifyDeployment depCfg: destApp, namespace: '6260-tasks-prod', replicaCount: '1', verbose: 'false', verifyReplicaCount: 'true', waitTime: '', waitUnit: 'sec'
                openshiftVerifyService namespace: '6260-tasks-prod', svcName: destApp, verbose: 'false'
            }

            stage('Switch over to new Version') {
                echo "Switching Production application to ${destApp}."
                sh 'oc patch route tasks -n 6260-tasks-prod -p \'{"spec":{"to":{"name":"' + destApp + '"}}}\''
            }
        }
    }
  }

// Convenience Functions to read variables from the pom.xml
// Do not change anything below this line.
// --------------------------------------------------------
// Those lines were modified to ease my life for the homework. Using String instead of just def let the IDE help me.
String getVersionFromPom(pom) {
    def matcher = readFile(pom) =~ '<version>(.+)</version>'
    matcher ? matcher[0][1] : null
}

String getGroupIdFromPom(pom) {
    def matcher = readFile(pom) =~ '<groupId>(.+)</groupId>'
    matcher ? matcher[0][1] : null
}

String getArtifactIdFromPom(pom) {
    def matcher = readFile(pom) =~ '<artifactId>(.+)</artifactId>'
    matcher ? matcher[0][1] : null
}
